title:
description:      Codes samples, tips, experiments,..
disqus_shortname: bertrandggithubio
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://bertrandg.github.io

# Owner/author information
owner:
  name:           Bertrand Gaillard
  avatar:         avatar.jpg
  bio:            "Web Developer<br>Lyon, FRANCE"
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        bertrandggg
  github:         http://github.com/bertrandg
  stackexchange:  http://stackoverflow.com/users/4717011/bertrandg
  linkedin:       http://www.linkedin.com/pub/bertrand-gaillard/21/3bb/a63
  flickr:         https://www.flickr.com/photos/37553716@N05/

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-55413226-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: yourphototravel.com
    url: http://www.yourphototravel.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 2

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
